#!/bin/bash

echo "Which ovftool:"
which ovftool
echo "Whoami:"
whoami


ESXI_HOST="10.196.5.203"
ESXI_USER="root"
ESXI_PASS="12txbu!@"
DATASTORE="datastore1"
NETWORK_NAME="VM Network"

OVA_PATH="/home/test/ce-host*ova"

START=1
END=1

for i in $(seq $START $END); do
  VM_NAME="CE-Host-189.$i"
  echo "Deploying VM: $VM_NAME"

  /home/test/ovftool/ovftool \
    --acceptAllEulas \
    --name="$VM_NAME" \
    --datastore="$DATASTORE" \
    --network="$NETWORK_NAME" \
    --diskMode=thin \
    --powerOn \
    "$OVA_PATH" \
    "vi://$ESXI_USER:$ESXI_PASS@$ESXI_HOST/"

  if [ $? -eq 0 ]; then
    echo "✅ $VM_NAME deployed and powered on."
  else
    echo "❌ Failed to deploy $VM_NAME"
  fi

  echo "-------------------------------"
done

pipeline {
    agent any
    stages {
        stage('Deploy') {
            steps {
                sh 'bash deploy.sh'
            }
        }
    }
}
